apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-editor-binding
  namespace: rbac-test
subjects:
- kind: ServiceAccount
  name: rbac-user
  namespace: rbac-test
roleRef:
  kind: Role
  name: scale-editor
  apiGroup: rbac.authorization.k8s.io
