apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbac-test
  name: scale-editor
rules:
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  # , "update", "patch"
  verbs: ["get"]
