apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbac-user-clusterrole
rules:
# - apiGroups: [""]
#   resources: ["pods", "events", "persistentvolumeclaims", "secrets", "services", "configmaps"]
#   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# - apiGroups: ["apps"]
#   resources: ["deployments"]
#   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
